# Generated by Django 3.0.8 on 2020-08-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stolb', models.CharField(max_length=20, unique=True)),
                ('m_coun', models.IntegerField()),
            ],
        ),
    ]
