# Generated by Django 3.0.8 on 2020-08-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test1', models.CharField(max_length=20)),
                ('test2', models.CharField(max_length=20)),
            ],
        ),
    ]
