# Generated by Django 3.0.8 on 2020-08-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0002_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stolb', models.CharField(max_length=20)),
                ('m_coun', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
